name: Build Eureka Service

on:
  push:
    paths:
      - 'EurekaService/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Eureka Service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: chmod +x mvnw
        working-directory: EurekaService
      - run: ./mvnw clean install
        working-directory: EurekaService
